server:
  port: 2011
#spring:
#  cloud:
#    gateway:
#      routes:
#      - predicates:
#        - Path=/java/**
#        filters:
#        - StripPrefix=1
#        uri: "http://localhost:1302/consumer"