server:
  port: 2102

spring:
  application:
    name: my-config-server
  profiles:
    active: native
  # \u914D\u7F6E\u4E2D\u5FC3
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/
#spring:
#  application:
#    name: config-server
#  cloud:
#    config:
#      label: dev
#      server:
#        git:
#          password: ''
#          searchPaths: respo
#          uri: https://github.com/itrimer/spring-cloud-dev/
#          username: ''